cd ..
git clone hackataller@svn-5550.devcloud.hosting.acquia.com:hackataller.git

echo '\n #Go to cloned repo and checkout/pull branch. \n'

cd hackataller
git pull
git checkout $BRANCH_NAME
git pull origin $BRANCH_NAME

echo '\n #Remove docroot from Acquia and copy the one generated by kraftwagen \n'
sudo rm -rf docroot
cp -LR $SEMAPHORE_PROJECT_DIR/docroot/ .

echo '\n #If copy was ok, add it all to Acquia repo and push \n'

git add --all .
git commit -m "Automatic deploy by Taller's Semaphore"
git push origin $BRANCH_NAME
