<?php

/**
 * @file
 * Contains ticket.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ticket_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ticket module.
    case 'help.page.ticket':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('') . '</p>';
      return $output;

    default:
  }
}
